# Generated by Django 4.2.7 on 2023-11-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcounterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
